name: CPython GMIC Windows build
# Imitating https://github.com/vinecopulib/pyvinecopulib/blob/master/.github/workflows/pypi.yml 
# and https://github.com/joerick/cibuildwheel/blob/master/.github/workflows/test.yml

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v1
      # Using https://github.com/marketplace/actions/setup-msys2
      - name: Using "Setup MSYS2" contrib
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: make git
      - run: git describe --dirty
      - name: build on windows
        working-directory: ./
        env:
          TWINE_PASSWORD_GITHUB_SECRET: ${{ secrets.TWINE_PASSWORD_GITHUB_SECRET }} # For build_tools.bash 11_send_to_pypi
        run: |
          pacman --noconfirm -S wget mingw-w64-x86_64-curl mingw-w64-x86_64-python-pip mingw-w64-x86_64-python python-devel mingw-w64-x86_64-gcc mingw-w64-x86_64-zlib mingw-w64-x86_64-libjpeg-turbo mingw64/mingw-w64-x86_64-pkgconf mingw-w64-x86_64-libpng mingw-w64-x86_64-libtiff mingw64/mingw-w64-x86_64-fftw mingw-w64-x86_64-toolchain
          pacman --noconfirm -S mingw-w64-x86_64-python-numpy
          # Add complementary pkg-config .pc lookup path
          export PKG_CONFIG_PATH=/usr/lib/pkgconfig/:$PKG_CONFIG_PATH
          pkg-config --list-all
          pkg-config libjpeg --libs --cflags
          pkg-config libpng --libs --cflags
          pkg-config libtiff-4 --libs --cflags
          pkg-config zlib --libs --cflags
          pkg-config libcurl --libs --cflags
          pkg-config libcurl --libs --cflags
          which python
          python --version
          gcc --version
          g++ --version
          which pip
          pip --version
          pip install dev-requirements.txt
          bash build_tools.bash 1_clean_and_regrab_gmic_src
          bash build_tools.bash 2b_compile_debug
          ldd $(find -name *.dll)
          bash build_tools.bash 3_test_compiled_so format
          bash build_tools.bash 4b_build_windows_portable_wheel
          bash build_tools.bash 5_test_wheel format
      - name: upload .whl debug build dir as artifact
        uses: actions/upload-artifact@v2
        with:
          name: gmic-py-windows-debug-dist-dir
          path: dist/
      - name: upload .dll debug build dir as artifact
        uses: actions/upload-artifact@v2
        with:
          name: gmic-py-windows-debug-build-dir
          path: build/
