name: CPython GMIC Manylinux 2010 & 2014 i686 & x86_64
# Ugly mix of https://github.com/htm-community/htm.core/blob/master/.github/workflows/build.yml and https://github.com/pypa/python-manylinux-demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
        plat: ['manylinux2010_x86_64', 'manylinux2010_i686', 'manylinux2014_x86_64', 'manylinux2014_i686']
        include:
          - plat: manylinux2010_i686
            docker_image: 'quay.io/pypa/manylinux2010_x86_64:latest'
            pre_cmd: linux32
          - plat: manylinux2010_x86_64
            docker_image: 'quay.io/pypa/manylinux2010_x86_64:latest'
            pre_cmd:
          - plat: manylinux2014_i686
            docker_image: 'quay.io/pypa/manylinux2014_686:latest'
            pre_cmd: linux32
          - plat: manylinux2014_x86_64
            docker_image: 'quay.io/pypa/manylinux2014_x86_64:latest'
            pre_cmd:
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: build, run packages on ${{ matrix.plat }} architecture and publish them to PyPI
        working-directory: ./cpython
        env:
          DOCKER_IMAGE: ${{ matrix.docker_image }}
          PLAT: ${{ matrix.plat }}
          CMD: ${{ matrix.cmd }}
        run: |
          for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done
          bash 33_build_manylinux.sh && bash 11_send_to_pypi.sh
